name: linux-app-build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - run: sudo apt-get update

      - run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

      - run: flutter pub get

      - run: flutter build linux --release

      - name: Package Linux app
        run: |
          cd build/linux/x64/release
          zip -qq -r -9 ToothFile-linux.zip bundle

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToothFile-linux-zip
          path: build/linux/x64/release/ToothFile-linux.zip
          if-no-files-found: error

      - name: Upload Linux release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/linux/x64/release/ToothFile-linux.zip
          tag: build-${{ github.run_number }}-linux
          release_name: ToothFile Linux build ${{ github.run_number }}
          overwrite: true
          body: Automated Linux app build